"""Managed beets integration: config generation and import runs.

The vendored beets (see fetchdeps.PIP_PACKAGES) is configured so a plain
``beet import`` reproduces the user's MusicBrainz Picard setup:

* paths use the ``mlo_dir`` album template field computed by the bundled
  ``mloplugin`` from MLO's actual naming script (server/naming.py), so
  beets organizes files into the identical folder structure;
* the plugin adds locale translations (MusicBrainz aliases), work /
  movement tags from work relationships, and release-type
  capitalization (EP uppercased, others Title Case);
* imports run headless: ``quiet`` mode auto-applies strong MusicBrainz
  matches and falls back to "as-is" for weak ones.
"""
import os
import subprocess
import sys

from mlo.config import load_config
from mlo.fetchdeps import pip_package_path
from mlo.tools import python_pkg_path

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(REPO_ROOT, "server", "data")
PLUGIN_DIR = os.path.join(REPO_ROOT, "server", "beets")


def db_path():
    return os.path.join(DATA_DIR, "beets-library.db")


def config_path():
    return os.path.join(DATA_DIR, "beets-config.yaml")


def _yq(text):
    """Quote a string for YAML with forward slashes (Windows-safe)."""
    return '"' + str(text).replace("\\", "/").replace('"', "'") + '"'


def generate_config(cfg=None):
    """Render beets config.yaml from MLO config; returns the YAML text."""
    cfg = cfg or load_config()
    locale = str(cfg.get("beets_locale") or "en").strip()
    lines = [
        "# Generated by MusicLibraryOptimizer — edits are overwritten.",
        f"directory: {_yq(cfg.get('music_folder') or '')}",
        f"library: {_yq(db_path())}",
        "",
        "import:",
        "  copy: no",
        "  move: yes",
        "  write: yes",
        "  quiet: yes",
        "  quiet_fallback: asis",
        "  duplicate_action: skip",
        f"  languages: {_yq(locale)}",
        "",
        "paths:",
        # %func{...} is beets template-function call syntax: %mlo_dir
        # computes the album folder from MLO's naming script and $mlo_file
        # (a plugin item field) supplies the "D-TT Title" filename.
        "  default: %mlo_dir{$mlo_file}",
        "",
        "plugins: [mloplugin]",
        f"pluginpath: [{_yq(PLUGIN_DIR)}]",
        "",
        "mloplugin:",
        f"    locale: {_yq(locale)}",
        f"    translations: {'yes' if cfg.get('beets_translations', True) else 'no'}",
        f"    work_movement: {'yes' if cfg.get('beets_work_movement', True) else 'no'}",
        f"    release_type_caps: {'yes' if cfg.get('beets_release_type_caps', True) else 'no'}",
        "",
        "musicbrainz:",
        "  enabled: yes",
        "  genres: yes",
        "",
        # Tag writes come from the plugin's own logic through MLO's tag
        # layer, so beets' own asis/autotag writes stay Picard-compatible.
        "match:",
        "  ignored_media: ['Data CD', 'DVD', 'DVD-Video', 'Music DVD',",
        "                  'VCD', 'SVCD', 'UMD', 'VHS']",
    ]
    text = "\n".join(lines) + "\n"
    return text


def write_config(cfg=None):
    text = generate_config(cfg)
    os.makedirs(DATA_DIR, exist_ok=True)
    tmp = config_path() + ".tmp"
    with open(tmp, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    os.replace(tmp, config_path())
    return config_path()


def beets_available():
    """(version_label, plugin_dir) when vendored beets is installed."""
    if not pip_package_path("beets"):
        return None
    from mlo.fetchdeps import PINNED
    return PINNED["beets"]["version"]


def _python():
    """A real interpreter for the beets subprocess; sys.executable points at
    the frozen server exe in PyInstaller builds."""
    if not getattr(sys, "frozen", False):
        return sys.executable
    import shutil
    for cand in ("python", "python3", "py"):
        found = shutil.which(cand)
        if found:
            return found
    return sys.executable


def _env():
    """Env for the beets subprocess: repo root + vendored beets on sys.path."""
    pkg = python_pkg_path("beets")
    env = dict(os.environ)
    parts = [REPO_ROOT]
    if pkg:
        parts.insert(0, pkg)
    env["PYTHONPATH"] = os.pathsep.join(parts) + os.pathsep + env.get("PYTHONPATH", "")
    env["PYTHONIOENCODING"] = "utf-8"
    return env


def run_beets_import(paths, cfg=None, timeout=7200):
    """Run `beet import` over the given folders headlessly.

    Returns (ok, output). The generated config is rewritten first so the
    current naming script / plugin settings always apply.
    """
    if not paths:
        return False, "no paths given"
    if not beets_available():
        return False, "beets is not installed — install it from Settings → Beets"
    cfg = cfg or load_config()
    conf = write_config(cfg)
    cmd = [
        _python(), "-m", "beets",
        "--config", conf,
        "import", "--quiet", "--group-albums",
        *paths,
    ]
    try:
        proc = subprocess.run(
            cmd, cwd=REPO_ROOT, env=_env(),
            capture_output=True, text=True, encoding="utf-8",
            errors="replace", timeout=timeout,
        )
    except subprocess.TimeoutExpired:
        return False, "beets import timed out"
    output = ((proc.stdout or "") + (proc.stderr or "")).strip()
    if proc.returncode != 0:
        tail = "\n".join(output.splitlines()[-15:])
        return False, f"beets import failed (rc={proc.returncode}):\n{tail}"
    return True, output
