"""Managed slskd (Soulseek) integration.

slskd (https://github.com/slskd/slskd) is a single-binary Soulseek client
with a REST API. It is vendored into .dependencies like every other tool;
this module:

  * generates slskd's YAML config from MLO settings (credentials, profile
    description, listen/web ports, upload/download limits, shares = the
    music folder, download dir),
  * spawns/monitors the process,
  * exposes a thin REST client (search, downloads, transfers, profile).

The generated config lives at server/data/slskd.yaml; a random web API key
is minted per start and kept in memory (the web UI is bound to localhost).
"""
import os
import re
import subprocess
import threading
import time
import uuid

import httpx

from mlo.config import load_config
from mlo.fetchdeps import installed_path
from server.beetscfg import DATA_DIR, REPO_ROOT

CONFIG_PATH = os.path.join(DATA_DIR, "slskd.yaml")

_proc_lock = threading.Lock()
_proc = {"proc": None, "api_key": None, "started_at": 0.0}

CREATE_NO_WINDOW = 0x08000000


# --------------------------------------------------------------------------- #
# Binary + config
# --------------------------------------------------------------------------- #
def slskd_exe():
    d = installed_path("slskd")
    if d:
        for name in ("slskd.exe", "slskd"):
            p = os.path.join(d, name)
            if os.path.isfile(p):
                return p
    return None


def slskd_installed():
    return slskd_exe() is not None


def _yq(text):
    return '"' + str(text).replace("\\", "/").replace('"', "'") + '"'


def download_dir(cfg=None):
    """Where slskd saves files (<music folder>/.mlo_downloads by default)."""
    cfg = cfg or load_config()
    d = str(cfg.get("soulseek_download_dir") or "").strip()
    if d:
        return d
    music = str(cfg.get("music_folder") or "").strip()
    if music:
        return os.path.join(music, ".mlo_downloads")
    return os.path.join(DATA_DIR, "downloads")


def generate_yaml(cfg=None):
    """Render slskd config; returns (yaml_text, api_key)."""
    cfg = cfg or load_config()
    api_key = uuid.uuid4().hex
    username = str(cfg.get("soulseek_username") or "").strip()
    password = str(cfg.get("soulseek_password") or "").strip()
    description = str(cfg.get("soulseek_description") or "").strip()
    listen_port = int(cfg.get("soulseek_listen_port") or 50000)
    web_port = int(cfg.get("soulseek_web_port") or 5030)
    up_limit = int(cfg.get("soulseek_up_limit") or 0)
    down_limit = int(cfg.get("soulseek_down_limit") or 0)
    music = str(cfg.get("music_folder") or "").strip()
    downloads = download_dir(cfg)

    lines = [
        "# Generated by MusicLibraryOptimizer — edits are overwritten.",
        "web:",
        f"  port: {web_port}",
        "  authentication:",
        "    disabled: true",
        "    api_keys:",
        "      mlo:",
        f"        key: {api_key}",
        "        role: readwrite",
    ]
    if username:
        lines += [
            "authentication:",
            f"  username: {_yq(username)}",
            f"  password: {_yq(password)}",
        ]
    lines += [
        "soulseek:",
        f"  username: {_yq(username)}",
        f"  password: {_yq(password)}",
        f"  description: {_yq(description)}",
        "  listen_ip_address: 0.0.0.0",
        f"  listen_port: {listen_port}",
        f"  global_upload_limit: {up_limit}",
        f"  global_download_limit: {down_limit}",
        "dirs:",
        f"  downloads: {_yq(downloads)}",
        f"  incomplete: {_yq(os.path.join(downloads, '.incomplete'))}",
    ]
    if music:
        lines += [
            "shares:",
            "  directories:",
            f"    - {_yq(music)}",
            "  filters:",
            "    - '\\.mlo_trash'",
        ]
    text = "\n".join(lines) + "\n"
    return text, api_key


def write_config(cfg=None):
    text, api_key = generate_yaml(cfg)
    os.makedirs(DATA_DIR, exist_ok=True)
    tmp = CONFIG_PATH + ".tmp"
    with open(tmp, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    os.replace(tmp, CONFIG_PATH)
    return api_key


# --------------------------------------------------------------------------- #
# Process management
# --------------------------------------------------------------------------- #
def is_running():
    with _proc_lock:
        proc = _proc["proc"]
        if proc is None:
            return False
        if proc.poll() is not None:
            _proc["proc"] = None
            return False
        return True


def web_up(cfg=None):
    """True when something answers on the slskd web port (any process)."""
    try:
        with httpx.Client(base_url=_base_url(cfg), timeout=2.0) as client:
            r = client.get("/application", headers={"Accept": "application/json"})
            return r.status_code == 200
    except Exception:
        return False


def start(cfg=None):
    """Spawn slskd; returns (started, message). Idempotent.

    If an slskd from a previous backend run is still answering on the web
    port (orphaned child), it is adopted instead of spawning a duplicate.
    """
    with _proc_lock:
        if is_running():
            return True, "already running"
        exe = slskd_exe()
        if not exe:
            return False, "slskd is not installed"
        # slskd 0.26's single-file zip ships no wwwroot; it refuses to boot
        # without it even though only the REST API is needed here.
        try:
            os.makedirs(os.path.join(os.path.dirname(exe), "wwwroot"), exist_ok=True)
        except OSError:
            pass
        api_key = write_config(cfg)
        # Adopt an already-listening slskd (auth is disabled on localhost).
        try:
            with httpx.Client(base_url=_base_url(cfg), timeout=2.0) as client:
                r = client.get("/application", headers={"Accept": "application/json"})
                if r.status_code == 200:
                    _proc["api_key"] = None
                    _proc["started_at"] = time.time()
                    return True, "adopted already-running slskd"
        except Exception:
            pass
        kwargs = {}
        if os.name == "nt":
            kwargs["creationflags"] = CREATE_NO_WINDOW
        proc = subprocess.Popen(
            [exe, "--config", CONFIG_PATH, "--no-logo"],
            cwd=os.path.dirname(exe),
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            **kwargs,
        )
        _proc["proc"] = proc
        _proc["api_key"] = api_key
        _proc["started_at"] = time.time()
        return True, "started"


def stop():
    with _proc_lock:
        proc = _proc["proc"]
        _proc["proc"] = None
        if proc is None or proc.poll() is not None:
            return False
        try:
            proc.terminate()
            try:
                proc.wait(timeout=10)
            except subprocess.TimeoutExpired:
                proc.kill()
        except OSError:
            pass
        return True


# --------------------------------------------------------------------------- #
# REST client (slskd /api/v0)
# --------------------------------------------------------------------------- #
def _base_url(cfg=None):
    cfg = cfg or load_config()
    web_port = int(cfg.get("soulseek_web_port") or 5030)
    return f"http://127.0.0.1:{web_port}/api/v0"


def _headers():
    key = _proc["api_key"]
    h = {"Accept": "application/json"}
    if key:
        h["X-API-Key"] = key
    return h


def _request(method, path, json_body=None, timeout=30.0):
    with httpx.Client(base_url=_base_url(), timeout=timeout) as client:
        r = client.request(method, path, json=json_body, headers=_headers())
        r.raise_for_status()
        if r.status_code == 204 or not r.content:
            return None
        return r.json()


def wait_until_ready(timeout=25.0):
    """Poll the slskd application info endpoint until it answers."""
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            _request("GET", "/application", timeout=3.0)
            return True
        except Exception:
            time.sleep(0.7)
    return False


# --------------------------------------------------------------------------- #
# High-level operations
# --------------------------------------------------------------------------- #
def search(query, cfg=None):
    """Start a search; returns the search id for polling."""
    search_id = uuid.uuid4().hex[:20]
    body = {"id": search_id, "searchText": query}
    _request("POST", "/searches", json_body=body, timeout=30.0)
    return search_id


def search_results(search_id, cfg=None):
    """Aggregate file responses for a finished/in-progress search."""
    try:
        state = _request("GET", f"/searches/{search_id}")
    except httpx.HTTPStatusError as e:
        if e.response is not None and e.response.status_code == 404:
            return {"state": "NotFound", "responses": []}
        raise
    responses = []
    try:
        resp_list = _request("GET", f"/searches/{search_id}/responses") or []
    except httpx.HTTPStatusError as e:
        if e.response is not None and e.response.status_code == 404:
            resp_list = []
        else:
            raise
    for r in resp_list or []:
        username = r.get("username") or ""
        slot = bool(r.get("hasFreeUploadSlot"))
        speed = int(r.get("uploadSpeed") or 0)
        queue = int(r.get("queueLength") or 0)
        for f in r.get("files") or []:
            responses.append({
                "username": username,
                "file": f.get("filename") or "",
                "size": int(f.get("size") or 0),
                "bitrate": f.get("bitrate"),
                "duration": f.get("duration"),
                "vbr": f.get("vbr"),
                "slot": slot,
                "speed": speed,
                "queue": queue,
            })
    return {
        "state": (state or {}).get("state"),
        "responseCount": (state or {}).get("responseCount"),
        "fileCount": (state or {}).get("fileCount"),
        "responses": responses,
    }


def enqueue_download(username, files, cfg=None):
    """Queue files for download: files = [{filename, size}]."""
    body = {"username": username, "files": files}
    _request("POST", "/downloads", json_body=body, timeout=30.0)
    return True


def downloads_state(cfg=None):
    """Full download transfer tree, grouped per user."""
    try:
        return _request("GET", "/transfers/downloads") or []
    except httpx.HTTPStatusError as e:
        if e.response is not None and e.response.status_code == 404:
            return []
        raise


def server_state(cfg=None):
    """Login status + server stats (or None when logged out)."""
    try:
        return _request("GET", "/server")
    except httpx.HTTPStatusError as e:
        if e.response is not None and e.response.status_code in (401, 403, 404, 503):
            return None
        raise


def user_info(username, cfg=None):
    """Remote user profile (speeds, slots, files shared)."""
    return _request("GET", f"/users/{username}/info", timeout=15.0)


def application_info(cfg=None):
    return _request("GET", "/application", timeout=5.0)


# --------------------------------------------------------------------------- #
# Importing completed downloads into the library
# --------------------------------------------------------------------------- #
def import_completed(cfg=None):
    """Move completed downloads into the music folder, one album per folder.

    slskd lays out downloads as <download dir>/<user>/<remote folder>/file.
    Each remote folder becomes an album folder in the library; loose files
    are gathered into a "Soulseek" album folder. Returns the list of new
    album paths.
    """
    import shutil

    cfg = cfg or load_config()
    folder = str(cfg.get("music_folder") or "").strip()
    if not folder or not os.path.isdir(folder):
        raise ValueError("music_folder not set or not found")
    ddir = download_dir(cfg)
    if not os.path.isdir(ddir):
        return []

    def unique_album_dir(name):
        safe = re.sub(r'[<>:"/\\|?*\x00-\x1f]', "", str(name)).strip().rstrip(".")
        dest = os.path.join(folder, safe or "Soulseek Download")
        n = 2
        while os.path.exists(dest):
            dest = os.path.join(folder, f"{safe} ({n})")
            n += 1
        return dest

    moved = []
    for user in sorted(os.listdir(ddir)):
        upath = os.path.join(ddir, user)
        if not os.path.isdir(upath):
            continue
        subs = [s for s in sorted(os.listdir(upath))
                if os.path.isdir(os.path.join(upath, s))]
        if subs:
            # one album per shared folder
            for s in subs:
                dest = unique_album_dir(s)
                shutil.move(os.path.join(upath, s), dest)
                moved.append(dest)
            # leftover loose files from this user -> their own album folder
            leftovers = [f for f in os.listdir(upath)
                         if os.path.isfile(os.path.join(upath, f))]
            if leftovers:
                dest = unique_album_dir(f"Soulseek {user}")
                os.makedirs(dest)
                for f in leftovers:
                    shutil.move(os.path.join(upath, f), os.path.join(dest, f))
                moved.append(dest)
            os.rmdir(upath)
        else:
            # user dir with only loose files -> single album folder
            dest = unique_album_dir(f"Soulseek {user}")
            shutil.move(upath, dest)
            moved.append(dest)
    # legacy layout: loose files directly in the download root
    loose = [f for f in sorted(os.listdir(ddir))
             if os.path.isfile(os.path.join(ddir, f))]
    if loose:
        dest = unique_album_dir("Soulseek")
        os.makedirs(dest)
        for f in loose:
            shutil.move(os.path.join(ddir, f), os.path.join(dest, f))
        moved.append(dest)
    return moved
